version: '3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - realdebrid:/torrents
      - plexconfig:/plexconfig
      - transcode:/transcode
      #- PATH to MEDIA. to be updated. 
    environment:
      - PLEX_UID=${USERID}
      - PLEX_GID=${USERID}
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${CLAIMTOKEN}
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  plex_debrid:
    image: itstoggle/plex_debrid
    volumes:
      - plexdebrid_config:/plexdebrid_config  # Replace /path/to/config with your actual path
    network_mode: host
    restart: unless-stopped

volumes:
  realdebrid:
    external: true
